name: Build GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npx parcel build src/index.html
      - name: Set dir up to only contain github-pages stuff
      - run: |-
          rm -rf node_modules package-lock.json package.json src
          mv dist/* .
          rmdir dist
      - name: Commit dist/ to github-pages branch
      - run: |-
          git checkout github-pages
          git config --global user.email "github-pages-bot@bleep-bloop.com"
          git config --global user.email "github-pages-bot"
          git add .
          git commit -m "Update website"
          git push